sonata_media:
    db_driver: doctrine_orm
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        footer:
            providers:
                - sonata.media.provider.image
            formats:
                basic: { width: 1200 , quality: 50 }

    cdn:
        server:
            path: /upload/media

    filesystem:
        local:
            # Directory for uploads should be writable
            directory: "%kernel.project_dir%/public/upload/media"
            create: false

    class:
        media: App\Entity\Media
        gallery: App\Entity\Gallery
        gallery_has_media: App\Entity\GalleryHasMedia