sonata_admin:
    
    title: 'OSOM'
    dashboard:
        groups:
            base:
                label: Panel administracyjny
                items:
                    - App\Admin\BoardMemberFunctionAdmin
                    - App\Admin\VoteTypeAdmin
                    - App\Admin\OrganizationAdmin
                roles: [ROLE_ADMIN]
            user:
                label: Panel użytkowników
                items:
                    - App\Admin\UserAdmin
                    - App\Admin\ResolutionProjectAdmin
                roles: [ROLE_ADMIN, ROLE_USER]
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        user_block: admin/user_block.html.twig
        layout: admin/main.html.twig
        
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
